loggers:
  default_logger:
    name: 'Default Logger'
    log_class: 2
    log_script_information: yes
    log_to_file: no
    log_name: 'logfile.txt'
  VK_logger:
    name: 'VK Logger'
    log_class: 2
    log_script_information: yes
    log_to_file: yes
    log_name: 'VK_log'



databases:
  default_db: 'C:/bot_databases/bot_database_v1.db'


smtp_servers:
  connection_timeout: 60
  servers:
    default_server:
      address: 'smtp.gmail.com'
      port: 587
    google:
      address: 'smtp.gmail.com'
      port: 587
    mail_ru:
     address: 'smtp.mail.ru'
     port: 465