loggers:
  default_logger:
    name: 'Default Logger'
    log_class: 2
    log_script_information: yes
    log_to_file: no
    log_name: 'logfile.txt'
  not_default_logger:
    name: 'SOME'



databases:
  default_db: 'C:\SQLite\bot_database_v1.db